Repository AY2122S1-CS2113T-W13-4/tp, pull requests merged in 2021-11, with the labels that each got.

#194 Add some minor changes to what is printed out + Update UG with new table formatting
  docs/UserGuide.md
  docs/developerGuideDiagrams/signInSequenceDiagram.png
  docs/developerGuideDiagrams/verificationComponent.png
  src/main/java/cooper/parser/CommandParser.java
  src/main/java/cooper/parser/SignInDetailsParser.java
  src/main/java/cooper/storage/SignInDetailsStorage.java
  src/main/java/cooper/ui/ForumUi.java
  src/main/java/cooper/ui/Ui.java
  src/main/java/cooper/ui/VerificationUi.java
  src/main/java/cooper/verification/Verifier.java
Labels: type.Task

#195 Resolve various issues
  src/main/java/cooper/Cooper.java
  src/main/java/cooper/command/AddCommand.java
  src/main/java/cooper/command/Command.java
  src/main/java/cooper/command/ProjectionCommand.java
  src/main/java/cooper/exceptions/AmountOutOfRangeException.java
  src/main/java/cooper/exceptions/InvalidProjectionException.java
  src/main/java/cooper/finance/FinanceManager.java
  src/main/java/cooper/ui/FinanceUi.java
Labels: type.Bug, priority.High

#200 Add some implementation sections to DG + Fix logout bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/developerGuideDiagrams/commandSequenceDiagram.png
  docs/developerGuideDiagrams/loginSequenceDiagram.png
  docs/developerGuideDiagrams/pdfSections.png
  docs/developerGuideDiagrams/refFrameRegistration.png
  docs/developerGuideDiagrams/registrationSequenceDiagram.png
  docs/developerGuideDiagrams/signInSequenceDiagram.png
  docs/developerGuideDiagrams/storageComponent.png
  docs/developerGuideDiagrams/uiComponent.png
  docs/developerGuideDiagrams/verificationComponent.png
  src/main/java/cooper/Cooper.java
  src/main/java/cooper/command/LogoutCommand.java
  src/main/java/cooper/command/ProjectionCommand.java
  src/main/java/cooper/exceptions/InvalidDocumentException.java
  src/main/java/cooper/exceptions/LogoutException.java
  src/main/java/cooper/parser/CommandParser.java
  src/main/java/cooper/parser/ParserBase.java
  src/main/java/cooper/storage/AvailabilityStorage.java
  src/main/java/cooper/storage/BalanceSheetStorage.java
  src/main/java/cooper/storage/CashFlowStorage.java
  src/main/java/cooper/storage/ForumStorage.java
  src/main/java/cooper/storage/MeetingsStorage.java
  src/main/java/cooper/storage/SignInDetailsStorage.java
  src/main/java/cooper/storage/Storage.java
  src/main/java/cooper/ui/FinanceUi.java
  src/main/java/cooper/ui/Ui.java
  src/main/java/cooper/ui/VerificationUi.java
  src/main/java/cooper/verification/Login.java
  src/main/java/cooper/verification/Registration.java
Labels: type.Enhancement, type.Task

#212 Added storage section for design and impl, fixed some minor bugs and refactored some parts of the code
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/developerGuideDiagrams/commandSequenceDiagram.png
  docs/developerGuideDiagrams/loadDataSequenceDiagram.png
  docs/developerGuideDiagrams/saveDataSequenceDiagram.png
  docs/developerGuideDiagrams/storageComponent.png
  src/main/java/cooper/Cooper.java
  src/main/java/cooper/command/AddCommand.java
  src/main/java/cooper/command/AvailabilityCommand.java
  src/main/java/cooper/command/AvailableCommand.java
  src/main/java/cooper/command/BsCommand.java
  src/main/java/cooper/command/CfCommand.java
  src/main/java/cooper/command/Command.java
  src/main/java/cooper/command/GenerateCommand.java
  src/main/java/cooper/command/ListCommand.java
  src/main/java/cooper/command/LogoutCommand.java
  src/main/java/cooper/command/MeetingsCommand.java
  src/main/java/cooper/command/PostAddCommand.java
  src/main/java/cooper/command/PostCommentCommand.java
  src/main/java/cooper/command/PostDeleteCommand.java
  src/main/java/cooper/command/PostListCommand.java
  src/main/java/cooper/command/ProjectionCommand.java
  src/main/java/cooper/command/ScheduleCommand.java
  src/main/java/cooper/parser/CommandParser.java
  src/main/java/cooper/parser/SignInDetailsParser.java
  src/main/java/cooper/resources/ResourcesManager.java
  src/main/java/cooper/storage/AvailabilityStorage.java
  src/main/java/cooper/ui/FinanceUi.java
  src/main/java/cooper/ui/ParserUi.java
  src/main/java/cooper/ui/VerificationUi.java
Labels: type.Enhancement, type.Task

#215 Fixed bug for Balance Sheet pdf
  src/main/java/cooper/finance/FinanceManager.java
  src/main/java/cooper/finance/pdfgenerator/BalanceSheetGenerator.java
  src/main/java/cooper/finance/pdfgenerator/CashFlowStatementGenerator.java
  src/main/java/cooper/finance/pdfgenerator/PdfGenerator.java
  src/main/resources/pdf/bs/bsCheckValue.tex
  src/main/resources/pdf/bs/bsTemplate.tex
  src/main/resources/pdf/cf/cfEntryTemplate.tex
  src/main/resources/pdf/cf/cfSummaryTemplate.tex
Labels: type.Task

#216 DG and UG Touch ups
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/developerGuideDiagrams/commandComponent.png
  docs/developerGuideDiagrams/commandSequenceDiagram.png
  docs/developerGuideDiagrams/junitPassed.png
  docs/developerGuideDiagrams/loginSequenceDiagram.png
  docs/developerGuideDiagrams/parserComponent.png
  docs/developerGuideDiagrams/registrationSequenceDiagram.png
  docs/developerGuideDiagrams/signInSequenceDiagram.png
  docs/developerGuideDiagrams/uiComponent.png
  docs/developerGuideDiagrams/verificationComponent.png
  docs/team/chrislangton.md
  docs/team/rrraaaeee.md
  docs/team/theeugenechong.md
  src/main/java/cooper/command/ExitCommand.java
  src/main/java/cooper/command/GenerateCommand.java
  src/main/java/cooper/command/HelpCommand.java
  src/main/java/cooper/command/LogoutCommand.java
  src/main/java/cooper/exceptions/InvalidDocumentException.java
  src/main/java/cooper/finance/pdfgenerator/PdfGenerator.java
  src/main/java/cooper/ui/FileIoUi.java
  src/main/java/cooper/ui/VerificationUi.java
Labels: type.Enhancement, type.Task

#218 Fix minor DG Bugs
  docs/DeveloperGuide.md
  docs/developerGuideDiagrams/forumComponent.png
  docs/developerGuideDiagrams/resourcesComponent.png
  src/main/java/cooper/command/CfCommand.java
  src/main/java/cooper/meetings/Meeting.java
  src/main/java/cooper/resources/ResourcesManager.java
  src/test/java/cooper/finance/FinanceManagerTest.java
  src/test/java/cooper/meetings/MeetingManagerTest.java
  src/test/java/cooper/parser/ParserTest.java
Labels: type.Task

#226 Update command formats for help command
  docs/DeveloperGuide.md
  src/main/java/cooper/command/AvailabilityCommand.java
  src/main/java/cooper/command/AvailableCommand.java
  src/main/java/cooper/command/MeetingsCommand.java
  src/main/java/cooper/command/ScheduleCommand.java
  src/main/java/cooper/ui/Ui.java
Labels: type.Enhancement

#227 Updates to Finance in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/developerGuideDiagrams/financeComponent.png
  src/main/java/cooper/command/AddCommand.java
  src/main/java/cooper/ui/FinanceUi.java
Labels: type.Task, priority.High

#228 Add Eugene's PPP
  docs/UserGuide.md
  docs/team/theeugenechong.md
Labels: type.Task, priority.High

#229 Remove page breaks at end of the file
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/theeugenechong.md
Labels: type.Task

#232 Standardized some of the formatting / diagrams throughout the DG
  docs/DeveloperGuide.md
  docs/developerGuideDiagrams/architectureDiagram.png
  docs/developerGuideDiagrams/financeComponent.png
  docs/developerGuideDiagrams/forumComponent.png
  docs/developerGuideDiagrams/forumSequenceDiagram.png
  docs/developerGuideDiagrams/registrationSequenceDiagram.png
  docs/developerGuideDiagrams/resourcesSequenceDiagram.png
  docs/developerGuideDiagrams/storageComponent.png
  src/main/java/cooper/verification/PasswordHasher.java
Labels: type.Task

#238 Minor tweaks to PPP
  docs/team/theeugenechong.md
Labels: type.Task

#240 add financeSequenceDiagram for 'add' function
  docs/DeveloperGuide.md
  docs/developerGuideDiagrams/financeSequenceDiagram.png
Labels: type.Task, priority.Medium

#243 Update the info part for add and list commands
  docs/UserGuide.md
Labels: type.Task

#244 Minor additions and fixes for DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/theeugenechong.md
Labels: type.Task, priority.High

#247 Changes to documentation UG/DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/chrislangton.md
Labels: type.Task, priority.Medium

#250 bug fix in projection
  src/main/java/cooper/finance/FinanceManager.java
Labels: type.Task, priority.High

#248 UG Fix
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#253 Changed logout section
  docs/UserGuide.md
  docs/team/theeugenechong.md
Labels: type.Task

#258 fix grammar in UG
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#265 add JavaDocs for finance components
  src/main/java/cooper/command/BsCommand.java
  src/main/java/cooper/finance/BalanceSheet.java
  src/main/java/cooper/finance/CashFlow.java
  src/main/java/cooper/finance/FinanceCommand.java
  src/main/java/cooper/finance/FinanceManager.java
  src/main/java/cooper/finance/Projection.java
  src/main/java/cooper/ui/FinanceUi.java
Labels: type.Task, priority.Medium

#269 add newline for projection print
  src/main/java/cooper/ui/FinanceUi.java
Labels: type.Task, priority.Medium

#272 finish PPP
  docs/team/chrislangton.md
Labels: type.Task, priority.High
