Repository AY2122S1-CS2113T-W13-4/tp, pull requests merged in 2021-10, with the labels that each got.

#42 Add JUnit Tests for Verifier class. Fixes #34
  build.gradle
  src/main/java/cooper/Cooper.java
  src/main/java/cooper/parser/CommandParser.java
  src/main/java/cooper/storage/Storage.java
  src/main/java/cooper/ui/Ui.java
  src/main/java/cooper/verification/Login.java
  src/main/java/cooper/verification/Registration.java
  src/main/java/cooper/verification/Verifier.java
  src/test/java/cooper/CooperTest.java
  src/test/java/cooper/verification/VerifierTest.java
Labels: type.Task, priority.High

#56 Add JUnit tests for login and registration in ParserTest class, fixes #34
  .gitignore
  src/main/java/cooper/command/AddCommand.java
  src/main/java/cooper/parser/CommandParser.java
  src/main/java/cooper/ui/Ui.java
  src/test/java/cooper/finance/FinanceManagerTest.java
  src/test/java/cooper/meetings/MeetingManagerTest.java
  src/test/java/cooper/parser/ParserTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
  tmp/storage.txt
Labels: type.Task

#61 add logging and assertions for FinanceManager
  cooperLogs.log
  src/main/java/cooper/finance/FinanceManager.java
  src/main/java/cooper/ui/Ui.java
Labels: type.Enhancement, priority.Medium

#66 Add quick start and login/registration section to user guide
  cooperLogs.log
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#132 Add Verification and Command components for DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/developerGuideDiagrams/commandComponent.png
  docs/developerGuideDiagrams/commandSequenceDiagram.png
  docs/developerGuideDiagrams/signInSequenceDiagram.png
  docs/developerGuideDiagrams/verificationComponent.png
  src/main/java/cooper/Cooper.java
  src/main/java/cooper/command/BsCommand.java
  src/main/java/cooper/command/CfCommand.java
  src/main/java/cooper/command/ProjectionCommand.java
  src/main/java/cooper/finance/FinanceCommand.java
  src/main/java/cooper/finance/FinanceManager.java
  src/main/java/cooper/parser/CommandParser.java
  src/main/java/cooper/parser/SignInDetailsParser.java
  src/main/java/cooper/ui/FinanceUi.java
  src/main/java/cooper/ui/Ui.java
  tmp/tmp_file_command.txt
Labels: type.Task

#137 Add JavaDocs for Verification segment plus a few other segments
  docs/DeveloperGuide.md
  docs/developerGuideDiagrams/architectureDiagram.png
  src/main/java/cooper/Cooper.java
  src/main/java/cooper/exceptions/InvalidAccessException.java
  src/main/java/cooper/exceptions/InvalidCommandFormatException.java
  src/main/java/cooper/exceptions/InvalidFileDataException.java
  src/main/java/cooper/exceptions/InvalidUserRoleException.java
  src/main/java/cooper/exceptions/LogoutException.java
  src/main/java/cooper/exceptions/UnrecognisedCommandException.java
  src/main/java/cooper/finance/pdfgenerator/BalanceSheetGenerator.java
  src/main/java/cooper/finance/pdfgenerator/CashFlowStatementGenerator.java
  src/main/java/cooper/finance/pdfgenerator/PdfGenerator.java
  src/main/java/cooper/parser/CommandParser.java
  src/main/java/cooper/parser/SignInDetailsParser.java
  src/main/java/cooper/resources/ResourcesManager.java
  src/main/java/cooper/storage/AvailabilityStorage.java
  src/main/java/cooper/storage/BalanceSheetStorage.java
  src/main/java/cooper/storage/CashFlowStorage.java
  src/main/java/cooper/storage/ForumStorage.java
  src/main/java/cooper/storage/MeetingsStorage.java
  src/main/java/cooper/storage/SignInDetailsStorage.java
  src/main/java/cooper/storage/Storage.java
  src/main/java/cooper/storage/StorageManager.java
  src/main/java/cooper/ui/FileIoUi.java
  src/main/java/cooper/ui/FinanceUi.java
  src/main/java/cooper/ui/ParserUi.java
  src/main/java/cooper/ui/Ui.java
  src/main/java/cooper/ui/VerificationUi.java
  src/main/java/cooper/util/Util.java
  src/main/java/cooper/verification/Login.java
Labels: type.Task

#190 UG Fixes + change output messages for signing in
  docs/UserGuide.md
  docs/_config.yml
  docs/developerGuideDiagrams/commandSequenceDiagram.png
  docs/developerGuideDiagrams/signInSequenceDiagram.png
  docs/developerGuideDiagrams/verificationComponent.png
  docs/userGuideImages/javaVersion.png
  src/main/java/cooper/Cooper.java
  src/main/java/cooper/parser/CommandParser.java
  src/main/java/cooper/parser/ParserBase.java
  src/main/java/cooper/parser/SignInDetailsParser.java
  src/main/java/cooper/storage/AvailabilityStorage.java
  src/main/java/cooper/storage/BalanceSheetStorage.java
  src/main/java/cooper/storage/CashFlowStorage.java
  src/main/java/cooper/storage/MeetingsStorage.java
  src/main/java/cooper/storage/SignInDetailsStorage.java
  src/main/java/cooper/ui/ParserUi.java
  src/main/java/cooper/ui/Ui.java
  src/main/java/cooper/ui/VerificationUi.java
  src/main/java/cooper/verification/Verifier.java
  tmp/tmp_command-data.properties
  tmp/tmp_sign-in-data.properties
Labels: priority.High
